### ISSUE TITLE
Fails to push to S3

### ISSUE THREAD

**Issue by lforehan** [novemberfiveco/s3pypi#10]
s3pypi runs `python setup` and stdout does not match an expected pattern.

### Reproduce
```
git clone https://github.com/dbarnett/python-helloworld.git
cd python-helloworld/
s3pypi --bucket pypi.example.com
```

### Error
```
Traceback (most recent call last):
  File "/usr/local/bin/s3pypi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/s3pypi/cli.py", line 21, in main
    package = Package.create(args.wheel)
  File "/usr/local/lib/python2.7/site-packages/s3pypi/package.py", line 53, in create
    raise RuntimeError(stdout)
RuntimeError: running sdist
running egg_info
creating helloworld.egg-info
writing helloworld.egg-info/PKG-INFO
writing top-level names to helloworld.egg-info/top_level.txt
writing dependency_links to helloworld.egg-info/dependency_links.txt
writing entry points to helloworld.egg-info/entry_points.txt
writing manifest file 'helloworld.egg-info/SOURCES.txt'
reading manifest file 'helloworld.egg-info/SOURCES.txt'
writing manifest file 'helloworld.egg-info/SOURCES.txt'
running check
creating helloworld-0.1
creating helloworld-0.1/helloworld
creating helloworld-0.1/helloworld.egg-info
making hard links in helloworld-0.1...
hard linking README -> helloworld-0.1
hard linking setup.py -> helloworld-0.1
hard linking helloworld/__init__.py -> helloworld-0.1/helloworld
hard linking helloworld/main.py -> helloworld-0.1/helloworld
hard linking helloworld.egg-info/PKG-INFO -> helloworld-0.1/helloworld.egg-info
hard linking helloworld.egg-info/SOURCES.txt -> helloworld-0.1/helloworld.egg-info
hard linking helloworld.egg-info/dependency_links.txt -> helloworld-0.1/helloworld.egg-info
hard linking helloworld.egg-info/entry_points.txt -> helloworld-0.1/helloworld.egg-info
hard linking helloworld.egg-info/top_level.txt -> helloworld-0.1/helloworld.egg-info
Writing helloworld-0.1/setup.cfg
creating dist
Creating tar archive
removing 'helloworld-0.1' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/helloworld
copying helloworld/__init__.py -> build/lib/helloworld
copying helloworld/main.py -> build/lib/helloworld
installing to build/bdist.macosx-10.11-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.11-x86_64
creating build/bdist.macosx-10.11-x86_64/wheel
creating build/bdist.macosx-10.11-x86_64/wheel/helloworld
copying build/lib/helloworld/__init__.py -> build/bdist.macosx-10.11-x86_64/wheel/helloworld
copying build/lib/helloworld/main.py -> build/bdist.macosx-10.11-x86_64/wheel/helloworld
running install_egg_info
Copying helloworld.egg-info to build/bdist.macosx-10.11-x86_64/wheel/helloworld-0.1-py2.7.egg-info
running install_scripts
creating build/bdist.macosx-10.11-x86_64/wheel/helloworld-0.1.dist-info/WHEEL
```

**Comment by lforehan** [comment]
I issued a pull request that fixed my issue.
https://github.com/novemberfiveco/s3pypi/pull/11

**Comment by mdwint** [comment]
Thanks for your contribution! I have added some test cases to verify that matching the package name works, including your sdist output.
