### ISSUE TITLE
Unable to list --extra-index-url in requirement.txt

### ISSUE THREAD

**Issue by RG-arulprashanth** [novemberfiveco/s3pypi#57]
I have a module that has a dependency from a private repository so when I list the reference to the private repository using --extra-index-url then s3pypi fails to read it as part of the install-requires in setup.py with the following error

error in test setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'--extra-'"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/s3pypi/package.py", line 74, in create
    stdout = check_output(cmd).decode().strip()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python3.7', 'setup.py', 'sdist', '--formats', 'gztar', 'bdist_wheel']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/s3pypi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/s3pypi/__main__.py", line 52, in main
    create_and_upload_package(args)
  File "/usr/local/lib/python3.7/site-packages/s3pypi/__main__.py", line 20, in create_and_upload_package
    package = Package.create(args.wheel, args.sdist)
  File "/usr/local/lib/python3.7/site-packages/s3pypi/package.py", line 76, in create
    raise RuntimeError(e.output.rstrip())
RuntimeError: b''

**Comment by mdwint** [comment]
Closing this because s3pypi 1.0.0 no longer creates distributions. See [CHANGELOG.md](https://github.com/novemberfiveco/s3pypi/blob/master/CHANGELOG.md) for details.
